language: java

services: docker

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk10
  - openjdk11
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: mvn install -B -V
after_success:
  - mvn clean test jacoco:report coveralls:report -Dcoveralls.token=$COVERALLS_TOKEN
