language: java

services: docker

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk10
  - openjdk11
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: mvn verify -Dgpg.skip=true